id: PBC7997D9
initial_creation_type: ocr
source_metadata:
  volumes:
    ba70b6b1fe71490bb6a4e1823024624d:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
